[[redirects]]
  from = "/create-iframe-room"
  to = "https://api.huddle01.com/api/v1"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"
    Server = "Caddy"
    X-Content-Type-Options = "nosniff"
    X-Dns-Prefetch-Control = "off"
    X-Download-Options = "noopen"
    X-Frame-Options = "SAMEORIGIN"
    X-Permitted-Cross-Domain-Policies = "none"
    X-XSS-Protection = "0"
  
